const regionalData = {
  regions: {
    "NYBPM Coounties": [
      "Bergen",
      "Bronx",
      "Dutchess",
      "Essex",
      "Fairfield",
      "Hudson",
      "Hunterdon",
      "Kings",
      "Mercer",
      "Middlesex",
      "Monmouth",
      "Morris",
      "Nassau",
      "New Haven",
      "New York",
      "Ocean",
      "Orange",
      "Passaic",
      "Putnam",
      "Queens",
      "Richmond",
      "Rockland",
      "Somerset",
      "Suffolk",
      "Sussex",
      "Union",
      "Warren",
      "Westchester",
    ],
    "NYMTC Planning Area": [
      "Bronx",
      "Kings",
      "Nassau",
      "New York",
      "Putnam",
      "Queens",
      "Richmond",
      "Rockland",
      "Suffolk",
      "Westchester",
    ],
  },
  sub_regions: {
    "Connecticut": ["Fairfield", "Litchfield", "New Haven"],
    "Long Island": ["Nassau", "Suffolk"],
    "Mid Hudson": [
      "Dutchess",
      "Orange",
      "Putnam",
      "Rockland",
      "Sullivan",
      "Ulster",
      "Westchester",
    ],
    "Mid Hudson South": ["Putnam", "Rockland", "Westchester"],
    "New Jersey": [
      "Bergen",
      "Essex",
      "Hudson",
      "Hunterdon",
      "Mercer",
      "Middlesex",
      "Monmouth",
      "Morris",
      "Ocean",
      "Passaic",
      "Somerset",
      "Sussex",
      "Union",
      "Warren",
    ],
    "New York City": ["Bronx", "Kings", "New York", "Queens", "Richmond"],
  },
};

export { regionalData };
